// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CleanupAwaitingRunsRequest = { older_than_hours: number, limit: number, dry_run: boolean, include_dashboard_owned: boolean, };
