// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LspConfigResponse = { enabled: boolean, servers: { [key in string]?: string }, inject_for_categories: Array<string>, };
