// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunArtifactPreviewResponse = { run_id: string, path: string, kind: string, mime: string, size_bytes: bigint, truncated: boolean, raw_url: string, content?: string, };
