// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeMessage = { id: string, run_id: string, created_at: string, session_id: string | null, from: string, to: string | null, author: string, kind: string, body: string, payload: Record<string, unknown>, };
