// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeWorkflowSummary = { workflow: string, status: string, completed_steps: number, total_steps: number, running_steps: Array<string>, ready_steps: Array<string>, pending_approval_step?: string, last_error?: string, };
