// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeSessionCounts } from "./RuntimeSessionCounts";
import type { RuntimeSessionSummary } from "./RuntimeSessionSummary";

export type RuntimeSessionsResponse = { generated_at: string, counts: RuntimeSessionCounts, sessions: Array<RuntimeSessionSummary>, };
