// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeWorkflowSummary } from "./RuntimeWorkflowSummary";

export type RuntimeSessionSummary = { id: string, kind: string, task: string, status: string, lifecycle: string, mode: string, provider?: string, started_at: string, finished_at?: string, age_seconds: bigint, duration_seconds?: bigint, output_preview?: string, workflow?: RuntimeWorkflowSummary, action_hint: string, };
