// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeMessage } from "./RuntimeMessage";

export type RuntimeMessagesResponse = { run_id: string, messages: Array<RuntimeMessage>, };
